env:
  global:
    - FORCE_COLOR=1

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: trusty
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - python2 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull
  - export NODE_OPTIONS="--max-old-space-size=2000"
  - export TOOL_NODE_FLAGS="--max-old-space-size=2000"
  - echo "GISTO_GITHUB_CLIENT_ID=$GISTO_GITHUB_CLIENT_ID" >> $TRAVIS_BUILD_DIR/.env
  - npm install codecov -g
  # configure build command for master or next (beta) branches
  - |
    if [ "$TRAVIS_BRANCH" == "next" ]; then
      export GISTO_PACK_COMMAND="npm run pack:beta"
    else
      export GISTO_PACK_COMMAND="npm run pack"
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -v '\n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm install npm@latest -g && npm ci && npm run test:coverage && $GISTO_PACK_COMMAND"
    else
      npm ci && npm run test:coverage && $GISTO_PACK_COMMAND && npm run build:web && echo "web.gistoapp.com" > ./web/CNAME && cd docs && npm install --no-package-lock && npm run build && cd -
    fi
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: web
    target-branch: master
    repo: Gisto/web.gistoapp.com
    on:
      branch: master
      condition: $TRAVIS_OS_NAME == "osx"
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: docs/public
    target-branch: master
    repo: Gisto/gisto.github.com
    on:
      all_branches: true
      condition: $TRAVIS_OS_NAME == "osx"

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

after_failure:
  - cd $TRAVIS_BUILD_DIR/dist
  - ls -lR | curl -F 'clbin=<-' https://clbin.com

after_success:
  - codecov
branches:
  only:
    - master
    - next
