language: node_js
node_js:
- '0.11'
env:
  global:
  - ENV_VAR_GISTO_VERSION="v0.2.6b"
  - secure: HrCtCbwu8IGmsT5WPrrSH7L0vjslefjq6aMhEfsG6gnB8ykxINV3yMWoJAy61rdvbG8scdEdIUNSbheHzS5cR6ZPd814YdF+M2l1EGctk1z7hEnpRQVh7i+tfeI5zh00Sz5jSdlvUc0iOKcboJWSWW+RpGVStk1yyyca/Kcg8hk=
  - secure: FYWLBoWTPfPe2ybJYrHzQOdY20Q2noOFfwVsYxoqClFpBaiEpYn9tzAHCbGIKgzzazqLky82l+s05Uggp6J8pK2TbT+D0ChWpMsrlOKV6DibinaEKkD1i2eN8dL0VeC4OrU75huobjvHRIvQwO2BrlvExiNj/lw+pmJujrl6J/Y=
  - secure: i4lkhkCZO26UkcTpwdNCZ0t3uqThu++9uVZwW2iHvVSQvurGH9f4dSV5FKbKmoB32jORBYwSuRViWYpU97S39Eybws3VMqO44PqWZGJyTAtnvkRICzeFErHvwSuI/DzSfmb3NxStnxcWLoKsYObw1cQFCuD8SPrAgDjT9efM/VM=
  - secure: MNojb7/ov7ueeu+xAQyijL5lX3TYOSl4sObWt8zAQddx26Fh2VKng8yspYXFK8gtQohggUjhinpuuXfMAsWysytoxes4T0h0Ixk1IHL4de3Mnbp8VX4uyShqjHWYAb+MFc7E/lnlQxsmmEI2vqvUzmzomJfNoqj/EDbnsJEahGM=
branches:
  only:
  - feature/travis-ci
install:
- npm install gulp bower --global
before_script:
- npm install
- gulp
- chmod +x ./build/script/node-webkit-build.sh
- export GISTO_TRAVIS_COMMIT_MESSAGE="$(git log --format=%B --no-merges -n 1)"
- export GISTO_DATE_NOW="$(date +"%Y%m%d")"
- echo "{"client_id":"$ENV_VAR_GISTO_CLIENT_ID","client_secret":"$ENV_VAR_GISTO_CLIENT_SECRET","server_token":"$ENV_VAR_GISTO_SERVER_TOKEN"}" >> dist/config.json
script:
- gulp version_bump --to=$ENV_VAR_GISTO_VERSION
- gulp dist && gulp dev
- ./build/script/node-webkit-build.sh --src=dist --name=gisto --win-icon=app/icon.ico --osx-icon=build/resources/osx/gisto.icns --osx-plist=build/resources/osx/Info.plist --build
after_success:
- "printf \"### git commit: $TRAVIS_COMMIT\n$GISTO_TRAVIS_COMMIT_MESSAGE\n\n[See on GitHub](https://github.com/Gisto/Gisto/commit/$TRAVIS_COMMIT)\" >> ./build/script/TMP/output/_h5ai.header.md"
- cd ./build/script/TMP && ln -s $GISTO_DATE_NOW latest
- mv output $GISTO_DATE_NOW
- rsync -avz -e ssh $GISTO_DATE_NOW latest $ENV_VAR_GISTO_NIGHTLY_SERVER:/home/gistoapp/public_html/
