image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

shallow_clone: true
clone_depth: 1

install:
  - ps: Install-Product node 8 x64
  - set CI=true
  - set NODE_ENV=production
  - npm install -g npm@latest cross-env rimraf @angular/cli
  - npm install

build_script:
  - npm run pack:build

test: off
